# Generated by Django 3.1.7 on 2021-02-28 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0004_modela_modelb1_modelb2_modelc1_modelc2_modeld_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RemoveField(
            model_name='modelb',
            name='A1',
        ),
        migrations.RemoveField(
            model_name='modelb',
            name='B1',
        ),
        migrations.RemoveField(
            model_name='modelb',
            name='C1',
        ),
        migrations.RemoveField(
            model_name='modelb',
            name='D1',
        ),
        migrations.RemoveField(
            model_name='modelc',
            name='A1',
        ),
        migrations.RemoveField(
            model_name='modelc',
            name='B1',
        ),
        migrations.RemoveField(
            model_name='modelc',
            name='C1',
        ),
        migrations.RemoveField(
            model_name='modelc',
            name='D1',
        ),
        migrations.AddField(
            model_name='modela',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='modela',
            name='date_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='modela',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_model_a', to='demo_app.product'),
        ),
        migrations.AddField(
            model_name='modela',
            name='variableA1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_d_model_a', to='demo_app.modeld'),
        ),
        migrations.AddField(
            model_name='modela',
            name='variableA2',
            field=models.CharField(choices=[('aa1', 'AA1'), ('aa2', 'AA2')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='modelb',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_model_b', to='demo_app.product'),
        ),
        migrations.AddField(
            model_name='modelb',
            name='variableB1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_b1_model_b_1', to='demo_app.modelb1'),
        ),
        migrations.AddField(
            model_name='modelb',
            name='variableB2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='modelb',
            name='variableB3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_b2_model_b_3', to='demo_app.modelb2'),
        ),
        migrations.AddField(
            model_name='modelb',
            name='variableB4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_b1_model_b_4', to='demo_app.modelb1'),
        ),
        migrations.AddField(
            model_name='modelb',
            name='variableB5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='modelc',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_model_c', to='demo_app.product'),
        ),
        migrations.AddField(
            model_name='modelc',
            name='variableC1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_c1_model_c_1', to='demo_app.modelc1'),
        ),
        migrations.AddField(
            model_name='modelc',
            name='variableC2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='modelc',
            name='variableC3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_c2_model_c_3', to='demo_app.modelc2'),
        ),
        migrations.AddField(
            model_name='modelc',
            name='variableC4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_c1_model_c_4', to='demo_app.modelc1'),
        ),
        migrations.AddField(
            model_name='modelc',
            name='variableC5',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='modela',
            name='buy_sell',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='modelb1',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modelb2',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modelc1',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modelc2',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modeld',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
